---
abstract: 'Produces warnings when unused variables are detected'
author:
  - 'Goro Fuji <gfuji(at)cpan.org>'
build_requires:
  Test::More: 0.62
  Test::Warn: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.46
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: warnings-unused
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.06
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.021
